In [28]:
import time


import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


# setup the figure and axes
fig = plt.figure(figsize=(8, 3))
ax1 = fig.add_subplot(111, projection='3d')

# fake data
_x = np.arange(4)
_y = np.arange(5)
_xx, _yy = np.meshgrid(_x, _y)
x, y = _xx.ravel(), _yy.ravel()

top = x + y
bottom = np.zeros_like(top)
width = depth = 1
fig.canvas.draw()
ax1.set_zlim(0,100)
ax1.set_title('Shaded')
# plt.show(block=False)
print(x)
print(y)
for i in range(100):
    bars = ax1.bar3d(x, y, bottom, width, depth, top)
    top += 1
    fig.canvas.draw()
    time.sleep(0.001)
    # plt.draw()
    bars.remove()

[0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3]
[0 0 0 0 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4]


In [44]:
from Cell2D import Cell2D, Cell2DViewer
import time
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


class Cell3DViewer(Cell2DViewer):
    def __init__(self, viewee):
        Cell2DViewer.__init__(self,viewee)
        fig = plt.figure()
        ax1 = fig.add_subplot(111, projection='3d')
        fig.canvas.draw()
    
    def draw(self):
        top = self.viewee.array
        n,m = top.shape
        print(n,m)
        bottom = np.zeros_like(top)
        width = depth = 1
        _xx, _yy = np.meshgrid(np.arange(n), np.arange(m))
        x, y = _xx.ravel(), _yy.ravel()
        print(x)
        print(y)
        print(top)
        print(bottom)
        bars = ax1.bar3d(x, y, bottom, width, depth, top)
        fig.canvas.draw()
        time.sleep(0.01)
        bars.remove()
        
    def animate(self):
        for i in range(100):
            self.step()
            self.draw()
        

In [45]:
from scipy.signal import correlate2d

class Diffusion(Cell2D):
    """Diffusion Cellular Automaton."""

    kernel = np.array([[0, 1, 0],
                       [1,-4, 1],
                       [0, 1, 0]])

    def __init__(self, n, m=None, r=0.1):
        """Initializes the attributes.

        n: number of rows
        m: number of columns
        r: diffusion rate constant
        """
        self.r = r
        m = n if m is None else m
        self.array = np.zeros((n, m), np.float)

    def step(self):
        """Executes one time step."""
        c = correlate2d(self.array, self.kernel, mode='same')
        self.array += self.r * c

In [46]:
diff = Diffusion(n=6, r=0.1)
diff.add_cells(3, 3, '111', '111', '111')
viewer = Cell3DViewer(diff)
viewer.animate()

6 6
[0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5]
[0 0 0 0 0 0 1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 5 5 5 5 5 5]
[[ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.1  0.1  0.1]
 [ 0.   0.   0.1  0.8  0.9  0.8]
 [ 0.   0.   0.1  0.9  1.   0.9]
 [ 0.   0.   0.1  0.8  0.9  0.8]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


/usr/local/lib/python3.4/dist-packages/mpl_toolkits/mplot3d/axes3d.py:2480: UserWarning: x, y, and z must be the same length.
  warnings.warn('x, y, and z must be the same length.')


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()